version: '1'

services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=sprint_retro_board
      - MYSQL_USER=sprintretroboard
      - MYSQL_PASSWORD=password
    networks:
      - localBridge

networks:
  localBridge: